### ISSUE TITLE
Please grant me admin rights to this repo

### ISSUE THREAD

**Issue by retog** [plazi/vernacularNames#1]
I should both add data as well as configure webhooks to ensure the correct workflow.

**Comment by tcatapano** [comment]
@retog: just added you as admin. Sorry for the delay

**Comment by retog** [comment]
thanks @tcatapano. For things to work with data-publishing and webhook I would also require https://github.com/plazi/Plazi-Communications/issues/914 to be solved. Who is managing the domain names?
